### ISSUE TITLE
Store suddenly resets app state to initial state

### ISSUE THREAD

**Issue by karlhaas** [ngrx/store#195] opened 2016-08-21 10:08 UTC
I replaced the ngrx router by the newest angular router (3.0.0-rc.1) and ugpraded ngrx store to version 2.1.2. We use a route /loader which is responsible for loading several objects from the backend. I receives the list of objects to be loaded via query params. Because it is possible that the loader gets called twice without switching to another route (triggered by guards) we do something like:

```
this.route.queryParams
      .map(queryParams => ({
         // extract the query Params
      }))
      .filter(// do nothing if params are empty)
      .switchMap(params => {
        let required = params.required;
        let optional = params.optional;
        return this.loaderService.load(required, optional);
      })
      .subscribe(result => {
        switch (result) {
          case some_error:
            // router go to some url
            break;
          default:
            // router go to requestet url
        }
      });
```

The loader service triggers actions in order to tell the effects to load stuff and watches the state in order to know if everything has been loaded.

Initially everything works as expected. But as soon as I do a log out and log in (which triggers the loader again) immediately after the ngOnDestroy method of the loader component gets called, something resets the state to the initial state.

All other state changes happen exactly after an action has been processed by the reducers but in this case the state changes to the initial state without an action.

Any ideas how I can debug this behavior or what could be wrong?

**Comment by karlhaas** [comment] 2016-08-21 10:49
Maybe I found the cause ... I wrote the following function:

```
export function getValue<T>(state$:Observable<T>):T {
  let value:T;
  state$.take(1).subscribe(val => value = val);
  return value;
}
```

in order to get a value from an observable and use it like:

```
let x = getValue(someService.getAnObservableSliceOfTheState())
```

if I change the function to:

```
export function getValue<T>(state$:Observable<T>):T {
  let value:T;
  state$.subscribe(val => value = val).unsubscribe();
  return value;
}
```

then it seems to work. There was a similar problem with ngrx router and rxjs version 5.0.0-beta.6. The router just stop to work whenever I used take(1) or first() on the route params.

Can somebody please explain why this happens?

**Comment by monad98** [comment] 2016-08-22 07:43
Same problem here.
But I can't figure out what the problem is.
This problem only happens with the latest version.

**Comment by trcollinson** [comment] 2016-08-25 21:44
I am seeing a very similar problem though I don't have a function like you @karlhaas. I just moved to rc5 and I am changing from @ngrx/router to @angular/router and updating to the module bootstrap method and such. I'll show a bit of my setup:

user reducer simplified:

```
export interface UserState {
    user: User;
    userLoggedIn: boolean;
}

export const userInitialState: UserState = {
    user: Object.assign({}, emptyUser),
    userLoggedIn: false
}

export const userReducer: ActionReducer<UserState> =
    ( state: UserState = userInitialState, action: Action ) => {

 // my switch and case for the reducer

}
```

patient reducer simplified

```
export interface PatientState {
    patient: Patient;
    patients: Patient[];
}

export const patientInitialState: PatientState = {
    patient: Object.assign({}, emptyPatient),
    patients: [],
}

export const patientReducer: ActionReducer<PatientState> =
    (state: PatientState = patientInitialState, action: Action) => {

// my switch and case for the reducer
}
```

app.module.ts

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Store, StoreModule } from '@ngrx/store';

import { App } from './app.component';

import { routes } from './app.routes';

import { PatientListComponent,
              LoginComponent } from './pages';

import { patientReducer,
              patientInitialState,
              userReducer,
              userInitialState } from './reducers';

@NgModule({
    bootstrap: [ App ],
    declarations: [
        App,
        PatientListComponent,
        LoginComponent
    ],
    imports: [
        BrowserModule,
        HttpModule,
        FormsModule,
        RouterModule.forRoot(routes, { useHash: true }),
        StoreModule.provideStore(
                                    { patient: patientReducer,
                                      user: userReducer },
                                    { patient: patientInitialState,
                                      user: userInitialState }
                                )
    ]
})

export class AppModule {}
```

app.component.ts

```
import { Component, ViewEncapsulation } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs/Rx';

@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styles: [
    require('normalize.css'),
    require('./app.css')
  ],
  template: require('./html/app.html')
})

export class App {
  user: Observable<User>;
  userLoggedIn: Observable<boolean>;

  constructor(
    private _store: Store<any>
  ) {
    this.user = _store.select( state => state.user.user );
    this.userLoggedIn = _store.select( state => state.user.userLoggedIn );
  }
```

Now I would run the application, move around the site, and the store would be reset to the initial state with every change. It might be helpful to show a bit of my routing which is pretty basic, honestly.

app.routes.ts

```
import { Routes, RouterModule } from '@angular/router';
import { PatientListComponent,
              LoginComponent } from './pages';

export const routes: Routes = [
    { path: '', component: LoginComponent },
    { path: 'home', component: LoginComponent },
    { path: 'patient-list', component: PatientListComponent }
];
```

Nothing real complicated there. Basic routing that points to a component. A snippet of my html looks like this:

app.html

```
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" routerLink="/">
        <img src="assets/img/svg-logo-color.svg">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav" [class.hidden]="!_auth.authenticated()">
            <li>
                <a routerLink='/patient-list'>Patient</a>
            </li>
        </ul>

    </div>
  </div>
</nav>
<router-outlet></router-outlet>
```

Again nothing very complicated. Any the store logger wasn't even working right.

# Temporary Solution (Important for potentially debugging the issue)

I actually got everything to work properly by adding one line to the app.component constructor:

```
import { Component, ViewEncapsulation } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs/Rx';

@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styles: [
    require('normalize.css'),
    require('./app.css')
  ],
  template: require('./html/app.html')
})

export class App {
  user: Observable<User>;
  userLoggedIn: Observable<boolean>;

  constructor(
    private _store: Store<any>
  ) {
    _store.subscribe( state => console.log('Initial App State: ', state)); // This is the line
    this.user = _store.select( state => state.user.user );
    this.userLoggedIn = _store.select( state => state.user.userLoggedIn );
  }
```

By subscribing to the store everything started working. It would hold on to the state in the rest of the application properly, the store logger worked, everything was peachy again. I am not sure what about that changed.

I don't mind just subscribing to it, but it seems like a bug somewhere in there. Any fix would be very welcome!

**Comment by trcollinson** [comment] 2016-08-25 22:29
With the help of @DzmitryShylovich I think I understand what changed now.

Store is just an observable. He found the following quote which is insightful:

> Cold observables start running upon subscription, i.e., the observable sequence only starts pushing values to the observers when Subscribe is called.

http://blog.thoughtram.io/angular/2016/06/16/cold-vs-hot-observables.html

The problem is that the observable is not accepting values until it is subscribed to. This explains why the line `_store.subscribe( state => console.log('Initial App State: ', state));` causes everything to work.

What changed when moving to rc5? Well I moved from ngrx/router to angular/router. My guess is that ngrx/router worked with the store and subscribed somehow to the observable on the initialization of the application. So, removing ngrx/router removed the initial subscribe and everything stopped working.

Thanks @DzmitryShylovich

**Comment by MikeRyanDev** [comment] 2016-08-27 14:08
I'm running into the same problem with upgrading the example-app to RC5. I'm going to block this issue until RC6 which bumps the version number of rxjs.

**Comment by MikeRyanDev** [comment] 2016-08-28 01:49
Also, I do want to make one correction: while `Store` is indeed an cold observable, it's [source](https://github.com/ngrx/store/blob/master/src/store.ts#L20) is actually [hot](https://github.com/ngrx/store/blob/master/src/state.ts#L10).

**Comment by mhamel06** [comment] 2016-08-31 17:33
I was running into the same issues but it appears that using rxjs-beta.11 has resolved the issue.
I am using the angular-builds a few versions behind master.

Now the following does not cause the store to reset when called inside canActivate.
I also no longer need to call store.subscribe() in the app component.

```
getState(store: Store<State>): State {
    let state: State;
    store.take(1).subscribe(s => state = s);
    return state;
}

canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
    this.appState = this.getState(this.store);
...
```

**Comment by brandonroberts** [comment] 2016-10-21 01:07
Closing as resolved

**Closed as completed by brandonroberts** 2016-10-21 01:07 UTC
Labels: bug

**Comment by abdulhaq-e** [comment] 2016-10-23 16:24
I have this issue as well. I think if the store is not subscribed to in the root component then this problem will occur.

I wonder why the store doesn't dispatch the `@ngrx/store/init` action at boot. Parts of this problem is related to this action. Using the devtools, I can see that this action is being dispatched at every route change (hence the store is being reset). However, if it's dispatched very early (i.e. at the root component) then the store won't reset itself as I said above.
