### ISSUE TITLE
Ngrx/store/init is Fired Twice

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/store#280] opened 2016-11-27 21:23 UTC
This seems like a bug to me...

I have created a simple reducer which logs out the action that comes in:

```
import {ActionReducer, Action} from "@ngrx/store";
import {State, intitialState} from "../state/main-state";
import {INCREMENT, EVENT_FROM_EFFECT} from "../actions/main-action-creator";

export const mainReducer: ActionReducer<State> =
  (state = intitialState, action: Action) => {

    console.log('Action came in! ' + action.type);

  };
```

But when I test this is chrome I get the "init" action firing twice. Is there any good reason for firing it twice? 

![jimsngrxeg](https://cloud.githubusercontent.com/assets/5354163/20651949/d9152500-b4bd-11e6-8323-770b1514e165.png)

**Comment by fxck** [comment] 2016-11-27 22:58
https://github.com/ngrx/store/pull/256

**Comment by JimLynchCodes** [comment] 2016-11-28 02:50
I'm not really following the actual development of this, just trying to use it in my own project. And now that I know there is a "probe" event being fired as one of the "inits" I feel better about it so you can close this issue when it's fixed or when ever you feel like it. thanks

**Comment by jon301** [comment] 2016-12-06 15:31
I have the same issue
It looks like 2 store instances are created (I see 2 instances in the dropdown menu in Redux DevTools)
This is problematic since the app binds to the 2nd one (which is empty because it initiliazes later) so you lose the state of the 1st one which may contains some data that could be loaded on app load

Any help is welcome 
Thanks !

**Comment by qdouble** [comment] 2016-12-07 06:41
If it's on a lazy loaded module, it could be related to router bug

**Comment by spali** [comment] 2016-12-14 11:57
not sure about the reason, but I worked around by moving my data module which is responsible for the state stuff to the root and loaded it directly in the app module instead of loading it in a my shared module.
I think @qdouble is not that wrong :)

**Comment by paishin** [comment] 2017-01-08 22:55
hey @spali, I have the same issue, init functions being called multiple times but I am already loading them in my app.module. Could you please share some more info on your solution?

**Comment by spali** [comment] 2017-01-09 09:28
Try loading the store module just in the bootstrapping module. This worked for me.

**Comment by mxchange** [comment] 2017-02-07 08:32
Probably related: https://github.com/angular/angular/issues/12869

**Comment by karolmie1** [comment] 2017-02-17 08:46
@paishin If you are using lazy modules thats definitely it. Either get rid of them, or downgrade, as describd in  angular/angular#12869. Init event fires twice by design. If it fires 4 times or more, then you have a problem.

**Comment by brandonroberts** [comment] 2017-02-17 13:37
The init event shouldn't fire twice even under normal circumstances. You should only provide store in your root AppModule's imports. If you're seeing it twice than that's a separate issue

**Comment by ilya-loskutov** [comment] 2017-05-23 20:52
Hi, 
same issue. Have you resolved it?

**Comment by mxchange** [comment] 2017-05-26 08:08
This should be resolved in the latest angular4, or use older router https://github.com/angular/angular/issues/12869

**Comment by robwormald** [comment] 2017-07-19 02:30
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!

**Closed as completed by robwormald** 2017-07-19 02:30 UTC
Labels: enhancement, v3.0.0
