### ISSUE TITLE
Selector fire even not changed

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#201] opened 2016-08-29 16:05 UTC
Hi, 
as according to this example app: https://github.com/ngrx/example-app,

When I dispatch an action to change **id** property on the store, 
the selector of **others properties** are calculate...

**steps to reproduce:**
click on change_name button. 
the event dispatch an action: change_name. 
the reducer return the change.
but the problem is it's notify the property **id** was changed also.

**Check the console after click on change_name button**

Here's the code to reproduce this problem: (https://plnkr.co/edit/JgPwUExl9AhnFTRkd5u1?p=preview)

**Comment by awerlang** [comment] 2016-08-29 16:19
A `.select(...)` operator is called every time the store has changed. A property was changed, so has the containing object. In the case of the `getId()` selector, even though it is called, the target of it isn't (any subscriber to `.let()`). In other words, you have put this verification in the wrong place.

**Comment by wizardnet972** [comment] 2016-08-31 06:50
@awerlang , when slice of the state change, all store is begin subscribe it's ture.
but why to re-process others models(selectors) who's subscribes to a different slice in the store?
for example I have two states: Login and Customer. and Two selectors accordingly.
when I dispatch an action to Login reducer, after return a new state, the let operator is invoke and calc the selectors. both. - I think this is not necessary, just calc the selector whos had change. do ya?

**Comment by awerlang** [comment] 2016-08-31 12:11
Let's take a look at the proposed selector:

``` js
export function getIdFromCustomer() {
  return (state$: Observable<any>) => state$
    .select(customer => {
      console.log('WHY?? IT NOT CHANGED IN CHNAGE_NAME ACTION');
      return customer.id;
    });
};
```

`store` invokes the `select` callback every time anything has changed. Because you select only the `id` property, any consumer of this selector will be invoked only this has really changed from a previous invocation. It does this though the `distinctUntilChanged` RxJS operator. If that were to be applied to the store itself, it wouldn't make a difference, because it's a single immutable object (the reference changes when any reducers return a new substate).

Some things to consider:
- The selector callback is hardly expensive;
- The selector callback should be pure, no visible side-effects;
- There's no point in calling `distinctUntilChanged()` before a `select()`
- There's no way the store would know in advance what selector's `select` should be called at any point of time.

Hope this helps.

**Comment by stephenlautier** [comment] 2016-09-01 12:02
I'm having the same "issue" and yesterday I was debugging this a bit and what i found strange (and to me I considered it as an issue), selectors callbacks gets invoked even if no changes were done to the store e.g. hasChanges was also false.

Is that intended? or is it a bug? IMO It shouldn't emit next on store when no changes has happened.

Currently I'm using version 2.0.1 (since i cant update just yet due to ionic2)

**Comment by awerlang** [comment] 2016-09-01 13:33
@stephenlautier have you read my comment above? https://github.com/ngrx/store/issues/201#issuecomment-243744919

If you still not convinced, just use the string overload: `store.select('state')`

**Comment by stephenlautier** [comment] 2016-09-01 14:26
@awerlang yes i did.. 

> store invokes the select callback every time anything has changed

My point is, nothing has changed, i do understand if something changes it will trigger :)

**Comment by awerlang** [comment] 2016-09-01 14:55
> My point is, nothing has changed, i do understand if something changes it will trigger :)

If _nothing_ has changed, it will not invoke the select callback due to this line: https://github.com/ngrx/store/blob/master/src/utils.ts#L28

You can verify this by dispatching an unknown action. 

But if _anything_ has changed, even if because of other reducers, it will invoke the select callback. This is by design, since the store is a single object at the root, composed from the substate from each reducer.

**Comment by stephenlautier** [comment] 2016-09-01 17:35
@awerlang hmm ok i will check a little bit again, and see if thats happening.

Last i was checking i dispatched an action and simply do `return state` and it was still calling selectors, and what i found a bit dodgy was that `state$.subscribe(value => this.next(value));`
https://github.com/ngrx/store/blob/master/src/state.ts#L20

Was still getting invoked, even when `return hasChanged ? nextState : state;` was false. Hence thats why i posted.

I will test out as you suggested and see whether it will also trigger selectors. Thanks.

**Comment by awerlang** [comment] 2016-09-01 17:55
If all you have is a `return state`, I don't think that should trigger any subscriber, because even though a new action was dispached nothing has actually changed. The line you pointed could be improved with a `.distinctUntilChanged()`. It is common to dispatch action that only effects handle, so triggering a change on the state because of this would be unnecessary.

At first I got your comment in the same vein of the OP. But you brought something different.

**Comment by MikeRyanDev** [comment] 2016-09-10 15:00
Just to summarize in case someone comes across this issue in the future:

When you do `store.select(fn)`, the selector function _will_ be called every time an action is dispatched. The result observable, however, should only emit an update when the piece of state you selected changes. The select operator is really just:

``` ts
store.map(fn).distinctUntilChanged()
```

**Closed as completed by MikeRyanDev** 2016-09-10 15:00 UTC

**Comment by lekhnath** [comment] 2017-03-11 07:16
**"@ngrx/core": "^1.2.0",
 "@ngrx/store": "^2.2.1"**

In following example where .map is use instead .select it works as expected. After each dispatch event the subscription function is called. Which is not the case in later example.

```
//WORKING EXAMPLE, WITH .map()
export class HomeComponent implements OnInit {

  counter$: Observable<number>;

  constructor(
    private store: Store<AppStore>
  ) {
    this.counter$ = store.map(state => state.counter);
  }

  ngOnInit() {

    setInterval(() => {
      console.log('dispatched'); // <- When this happens
      this.store.dispatch({
        type: INCREMENT
      }); 
    }, 1000);   

    this.counter$.subscribe((num) => {
      console.log('number is ', num); // -< this also happens
    });
  }
}
```
---

```
// NOT WORKING EXAMPLE WITH .select()
export class HomeComponent implements OnInit {

  counter$: Observable<number>;

  constructor(
    private store: Store<AppStore>
  ) {
    this.counter$ = store.select<number>('counter');
  }

  ngOnInit() {

    setInterval(() => {
      console.log('dispatched'); // <- When this happens
      this.store.dispatch({
        type: INCREMENT
      }); 
    }, 1000);   

    this.counter$.subscribe((num) => {
      console.log('number is ', num); //<- this DO NOT happens
    });
  }
}
```

BUG?

**Comment by awerlang** [comment] 2017-03-11 11:38
The difference between select and map, is that only when the value changes (!==) from the previous operation, it is passed through. Make sure your reducers is immutable. If you prefer, paste your reducer code here.

**Comment by mfreirehfexp** [comment] 2017-03-20 21:12
Hi, sorry if the question does not apply
What is the correct way to avoid the duplicates calls to the subscribe() when the state is an Object?
I mean, in `distinctUntilChanged()` this evaluates like this `{foo:1} === {foo:1} // false`, so it's called multiple times
I'm new to react so I'm kind a lost here.
Thank you!

**Comment by awerlang** [comment] 2017-03-20 22:43
Either pass a comparator or a key selector to `distinctUntilChanged()`.

http://stackoverflow.com/a/36316843/592792

**Comment by mfreirehfexp** [comment] 2017-03-21 02:35
Thank you! I'll look for that

**Comment by rernens** [comment] 2017-06-27 12:55
@awerlang I not sure to get your point.

I have an application state built out of for sub states as below 👍 

```
export interface AppState {
  i18n: fromMultilingual.IMultilingualState;
  router: RouterState;
  uiState: fromMyTalentsShared.IUiState;
  storeData: fromMyTalents.IStoreData;
  organizationState: fromMyTalents.IOrganizationState;
}

const reducers = {
  i18n: fromMultilingual.reducer,
//  sample: fromSample.reducer,
  router: routerReducer,
  uiState: fromMyTalentsShared.uiStateReducer,
  storeData: fromMyTalents.storeDataReducer,
  organizationState: fromMyTalents.organizationStateReducer,

};
```

my organizationState sub state is defined as following
```
// angular

// libs
import { TreeNode } from 'angular2-tree-component';

// app



export interface IOrganizationState {
  uiState: string;
  talentsUiState: string;
  talentID: string;
  groupID: string;
  entityID: string;
  nodes: TreeNode[];
  talent: any;
  group: any;
  entity: any;
  errorCode: string;
}

export const INITIAL_ORGANIZATION_STATE: IOrganizationState = {
  uiState: undefined,
  talentsUiState: undefined,
  talentID: undefined,
  groupID: undefined,
  entityID: undefined,
  nodes: [],
  talent: undefined,
  group: undefined,
  entity: undefined,
  errorCode: undefined
};

// selects specific slice from organization state
export const getOrganizationNodes = (state: IOrganizationState)  => state.nodes;
```

I am handling access to state slices in the following way

```
export const getOrganizationState = (state: AppState) => state.organizationState;
export const getOrganizationNodes = createSelector(getOrganizationState, fromMyTalents.getOrganizationNodes );

```

my reducers for the organizationState are as following

```
// lib
import * as _ from 'lodash';

// app
import { INITIAL_ORGANIZATION_STATE, IOrganizationState } from '../states/organization.state';
import { OrganizationState } from '../actions/index';

export function organizationStateReducer (organizationState: IOrganizationState = INITIAL_ORGANIZATION_STATE, action: OrganizationState.Actions): IOrganizationState {

  const newOrganizationState = _.cloneDeep( organizationState );

  switch (action.type) {

    case OrganizationState.ActionTypes.SET_UI:
      newOrganizationState.uiState = _.cloneDeep(action.payload);
      return newOrganizationState;

    case OrganizationState.ActionTypes.ORGANIZATION_NODES_LOADED:
    case OrganizationState.ActionTypes.ORGANIZATION_NODES_UPDATED:
      newOrganizationState.nodes = _.cloneDeep(action.payload);
      return newOrganizationState;

    case OrganizationState.ActionTypes.SELECT_TALENT:
      newOrganizationState.talentID = _.cloneDeep(action.payload);
      return newOrganizationState;

    case OrganizationState.ActionTypes.SET_TALENTS_UI:
      newOrganizationState.talentsUiState = _.cloneDeep(action.payload);
      return newOrganizationState;

    case OrganizationState.ActionTypes.TALENT_PROFILE_LOADED:
      newOrganizationState.talent = _.cloneDeep(action.payload);
      return newOrganizationState;

    case OrganizationState.ActionTypes.SET_ERROR:
      newOrganizationState.errorCode = _.cloneDeep(action.payload);
      return newOrganizationState;

    default:
      return organizationState;
  }
}
```

whatever action is issued on the organizationState, the following subscription get always invoked

```
this.nodes$ = this.store.select( getOrganizationNodes )
      .do( () => this.log.debug('Talents Treeview Component - data updated') )
      .map( ( nodes: TreeNode[] ) => _.cloneDeep( nodes ));
```

change is detected on on organizationState.nodes despite not being changed even if the Redux Devtools diff does not show any change in this slice of the state.


Am I doing something wrong or is there a pb somewhere ?
